In [ ]:
import numpy as np
emb1 = np.load('embeddings3.npy')

In [ ]:
np. set_printoptions(threshold=np. inf)

In [ ]:
emb1[1]

array([-5.82670979e-02, -3.11513484e-01,  6.59972429e-01,  2.63553500e-01,
        2.76910141e-02,  1.86004788e-01, -4.71713573e-01, -2.86024690e-01,
       -2.60197014e-01,  1.04803133e+00, -4.19297665e-01, -3.68777335e-01,
        7.89059877e-01,  8.34486112e-02, -5.58786392e-01, -3.60477030e-01,
        2.00314954e-01,  7.53338039e-01, -2.85849385e-02,  2.09736675e-01,
       -1.75095454e-01,  2.33060062e-01,  3.96008193e-01,  1.01749098e+00,
       -5.87201834e-01, -3.73546660e-01, -4.96379465e-01, -9.77540910e-02,
        5.77042848e-02,  8.04395676e-02,  2.98597246e-01,  1.44779623e-01,
        9.51093435e-02,  5.01024723e-03, -4.48881030e-01, -1.33436665e-01,
       -8.47538292e-01,  2.81232923e-01, -1.05911821e-01, -1.80482626e-01,
        4.11044091e-01,  3.85159366e-02, -2.42310047e-01,  2.04664290e-01,
        1.60714790e-01,  2.68908143e-01,  2.58445948e-01, -6.12451173e-02,
        4.62547600e-01,  3.46926749e-01,  9.07169282e-03, -4.94770706e-01,
        9.15459245e-02, -

In [ ]:
import numpy as np
import pandas as pd 
import os
import seaborn as sns
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from keras import Sequential
from keras import optimizers
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential,Model
from keras.layers import LSTM, Dense, Bidirectional, Input,Dropout,BatchNormalization,CuDNNLSTM, GRU, CuDNNGRU, Embedding, GlobalMaxPooling1D, GlobalAveragePooling1D, Flatten
from keras import backend as K
from keras import initializers, regularizers, constraints
from sklearn.model_selection import KFold, cross_val_score, train_test_split

In [ ]:
data= pd.read_csv("/content/MTL_KAN_train_2.csv")

In [ ]:
data

Unnamed: 0                                         translated  \
0           5533  ನಿಂಗಾಪ್ಪ ಹಟಗನ್ವಾರ್ ಅತ್ಯುತ್ತಮ ಮಾರ್ಗವೆಂದರೆ 4Uíyk...   
1           4490                                  ಸೂಪರ್ ಹಾಡಿತು ಗುರು   
2           6216                                        ಕೀಳು ಕಾಡಿಯೂ   
3           3196                               ನಾನ್ ಅಸ್ಥಾಪಿಸು madhe   
4           6064                                           ಪುಟ್ ದಿನ   
...          ...                                                ...   
4260        4468                                  ಸೂಪರ್ ಒಸಾಮ್ ಸಂಗೀತ   
4261        5645                                ಸೂಪರ್ ಟೋಗಾರಿ ಟಿಪ್ಪಿ   
4262        7118                                      ಬುರ್ಗುರ್ ಗುರು   
4263        7153                               ಸಸ್ಪೆರ್ ಸಾಂಗ್ ಶುಭಭರಣ   
4264        1194     ಬೆಲಾಗವಿಯಿಂದ ಅವೇನ್ ನದ್ರಿ ಶ್ರೀಭುಜ ನಾರಾಯಣ್ ಪ್ರೀತಿ   

                                                comment      sent  \
0     ningappa hutagannavar the best way is 4uíykhfj...   unknown   
1                                       Super sang guru  Positive   
2     ಕೇಳಿ ಕಾದಿರುವ ಬಾಂಧವರೇnಭುವಿಯಲ್ಲಿ ಅವನ ಅರಿತವರೆnಯಾರ...  Positive   
3                                   Nan uninstall madhe  Positive   
4               ಎಷ್ಟು ದಿನ ಆಯಿತು ಕೇಳಿ ಓ ತುಂಬಾ ಖುಷಿ ಆಯಿತು  Positive   
...                                                 ...       ...   
4260                                   Super osam music  Positive   
4261                               super toogari tipppa  Positive   
4262  ಸೂಪರ್ ಗುರು ಲಾಸ್ಟ್ ಅಲ್ಲಿ ಹೇಳಿದ್ರಲ್ಲ ತಿಕ ಹೊಡಿಯೋ ...     Mixed   
4263                    ಸೂಪರ್ ಸಾಂಗ್ ಹುಚ್ಚೆಬ್ಬಿಸುವ ಸಾಂಗ್  Positive   
4264      Avane nodri sriman narayan love from belagavi  Positive   

                                       off  
0                    Offensive_Untargetede  
1                            Not_offensive  
2     Offensive_Targeted_Insult_Individual  
3                            Not_offensive  
4                            Not_offensive  
...                                    ...  
4260                         Not_offensive  
4261                         Not_offensive  
4262                         Not_offensive  
4263                         Not_offensive  
4264                         Not_offensive  

[4265 rows x 5 columns]

In [ ]:
y = [0 for x in range(4265)]
for i in range(4265):
  if(data['sent'][i]=="unknown"):
    data['sent'][i]=0
    y[i]=0
  if(data['sent'][i]=="Positive"):
    data['sent'][i]=1
    y[i]=1
  if(data['sent'][i]=="Negative"):
    data['sent'][i]=2
    y[i]=2
  if(data['sent'][i]=="Mixed"):
    data['sent'][i]=3
    y[i]=3

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
/usr/lo

In [ ]:
y= [0 for x in range(4265)]
for i in range(4265):
  if(data['off'][i]=="Not_offensive"):
    data['off'][i]=0
    y[i]=0
  if(data['off'][i]=="Offensive_Targeted_Insult_Individual"):
    data['off'][i]=1
    y[i]=1
  if(data['off'][i]=="Offensive_Targeted_Insult_Group"):
    data['off'][i]=2
    y[i]=2
  if(data['off'][i]=="Offensive_Targeted_Insult_Other"):
    data['off'][i]=3
    y[i]=3
  if(data['off'][i]=='Offensive_Untargetede'):
    data['off'][i]=4
    y[i]=4

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/usr/local/lib/python3.7/dist-pac

In [ ]:
y=tf.keras.utils.to_categorical(
    y, num_classes=None, dtype='float32'
)

In [ ]:
X_features, Y_features, X_labels, Y_labels = train_test_split(emb1, y,  test_size=0.3,random_state=50)

In [ ]:
Y_labels

array([[1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1.

In [ ]:
X_features.shape

(2985, 768)

In [ ]:
X_features=np.array(X_features)

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix


In [ ]:
classifier = RandomForestClassifier(n_estimators = 500, criterion = 'entropy', random_state = 42)
classifier.fit(X_features, X_labels)

RandomForestClassifier(criterion='entropy', n_estimators=500, random_state=42)

In [ ]:
y_pred = classifier.predict(Y_features)

In [ ]:
y_pred

array([[1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0.

In [ ]:
from sklearn import metrics
from sklearn.metrics import classification_report
print("Accuracy:",metrics.accuracy_score(y_pred,Y_labels))
print(classification_report(y_pred,Y_labels))

Accuracy: 0.72578125
              precision    recall  f1-score   support

           0       0.96      0.76      0.85      1187
           1       0.14      1.00      0.25        20
           2       0.01      0.50      0.02         2
           3       0.00      0.00      0.00         0
           4       0.00      0.00      0.00         1

   micro avg       0.73      0.77      0.75      1210
   macro avg       0.22      0.45      0.23      1210
weighted avg       0.95      0.77      0.84      1210
 samples avg       0.73      0.73      0.73      1210



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
